import dotenv  from "dotenv";
dotenv.config();

export const{
    APP_PORT,
    DEBUG_MODE,
    DB_URL,
    APP_URL,
    WEB_URL,
    JWT_SECRET,
    REFRESH_SECRET,
    
    FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID,

    DISCORD_URL,
    DISCORD_WEBHOOK_ID,
    DISCORD_WEBHOOK_TOKEN,
    DISCORD_SHOULD_WAIT_FOR_RESPONSE,
    REDIS_URL,
    EMAIL_API_URL,
    EMAIL_ADMIN_ID,
    EMAIL_ADMIN_PASSWORD,

    NOTIFICATION_USERNAME,
    NOTIFICATION_KEY,
    KAFKA_USERNAME,
    KAFKA_PASSWORD,
    KAFKA_MECHANISM,
    KAFKA_BROKER1,
    KAFKA_CLIENT_ID,
    KAFKA_TOPIC
    
}= process.env;