# Use an official Node.js runtime as a base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /Backend

# Copy package.json and package-lock.json to the working directory
# COPY package*.json /Backend
# Copy the rest of the application code
COPY . /Backend

# Install dependencies
RUN npm install

# Expose the port that your application will run on
EXPOSE 5500

# Command to run your application
CMD ["npm", "start"]